"""
Assembly Teaching Agent Prompts
"""

from .system_prompt import SYSTEM_PROMPT
from .mode_prompts import REQUIREMENT_GUIDE_PROMPT, CODE_CHECK_PROMPT
from .tool_prompts import (
    TASK_DECOMPOSER_PROMPT,
    CODE_VALIDATOR_PROMPT,
    PROGRESS_EVALUATOR_PROMPT,
    HINT_GENERATOR_PROMPT
)

__all__ = [
    'SYSTEM_PROMPT',
    'REQUIREMENT_GUIDE_PROMPT',
    'CODE_CHECK_PROMPT',
    'TASK_DECOMPOSER_PROMPT',
    'CODE_VALIDATOR_PROMPT',
    'PROGRESS_EVALUATOR_PROMPT',
    'HINT_GENERATOR_PROMPT'
]
